parameters:
    # OpenWeatherMap services
    netgen_open_weather_map.weather.class: Netgen\Bundle\OpenWeatherMapBundle\Core\Weather
    netgen_open_weather_map.air_pollution.class: Netgen\Bundle\OpenWeatherMapBundle\Core\AirPollution
    netgen_open_weather_map.daily_forecast.class: Netgen\Bundle\OpenWeatherMapBundle\Core\DailyForecast
    netgen_open_weather_map.hour_forecast.class: Netgen\Bundle\OpenWeatherMapBundle\Core\HourForecast
    netgen_open_weather_map.ultraviolet_index.class: Netgen\Bundle\OpenWeatherMapBundle\Core\UltravioletIndex
    netgen_open_weather_map.weather_stations.class: Netgen\Bundle\OpenWeatherMapBundle\Core\WeatherStations
    # END of OpenWeatherMap services

    # Cache services
    netgen_open_weather_map.cache_handler.null.class: Netgen\Bundle\OpenWeatherMapBundle\Cache\Null
    netgen_open_weather_map.cache_handler.memcached.class: Netgen\Bundle\OpenWeatherMapBundle\Cache\Memcached
    netgen_open_weather_map.cache_handler.stash.class: Netgen\Bundle\OpenWeatherMapBundle\Cache\Stash
    netgen_open_weather_map.cache_handler.class: Netgen\Bundle\OpenWeatherMapBundle\Cache\HandlerInterface

    netgen_open_weather_map.memcached.class: Memcached
    # END of Cache services

    # Controllers
    netgen_open_weather_map.controller.weather.class: Netgen\Bundle\OpenWeatherMapBundle\Controller\WeatherController
    netgen_open_weather_map.controller.weather_stations.class: Netgen\Bundle\OpenWeatherMapBundle\Controller\WeatherStationsController
    netgen_open_weather_map.controller.ultraviolet_index.class: Netgen\Bundle\OpenWeatherMapBundle\Controller\UltravioletIndexController
    netgen_open_weather_map.controller.hour_forecast.class: Netgen\Bundle\OpenWeatherMapBundle\Controller\HourForecastController
    netgen_open_weather_map.controller.daily_forecast.class: Netgen\Bundle\OpenWeatherMapBundle\Controller\DailyForecastController
    netgen_open_weather_map.controller.air_pollution.class: Netgen\Bundle\OpenWeatherMapBundle\Controller\AirPollutionController
    # END of Controllers

    # Http
    netgen_open_weather_map.http.client.class: Netgen\Bundle\OpenWeatherMapBundle\Http\HttpClient
    # END of Http

    # Factories
    netgen_open_weather_map.factory.cache.class: Netgen\Bundle\OpenWeatherMapBundle\Factory\CacheHandlerFactory
    # END of Factories
services:
    # Factories
    netgen_open_weather_map.factory.cache:
        class: '%netgen_open_weather_map.factory.cache.class%'
        calls:
            - ['setContainer', ['@service_container']]
    # END of Factories

    # Http
    netgen_open_weather_map.http.client:
        class: '%netgen_open_weather_map.http.client.class%'
    # END of Http

    # Cache services
    netgen_open_weather_map.cache_handler:
        class: '%netgen_open_weather_map.cache_handler.class%'
        factory: ['@netgen_open_weather_map.factory.cache', getCacheHandler]
        arguments:
            - '$cache_settings.handler;netgen_open_weather_map$'

    netgen_open_weather_map.cache_handler.null:
        class: '%netgen_open_weather_map.cache_handler.null.class%'

    netgen_open_weather_map.cache_handler.memcached:
        class: '%netgen_open_weather_map.cache_handler.memcached.class%'
        arguments:
            - '@netgen_open_weather_map.memcached'

    netgen_open_weather_map.cache_handler.stash:
        class: '%netgen_open_weather_map.cache_handler.stash.class%'
        arguments:
            - '@stash'

    netgen_open_weather_map.memcached:
        class: '%netgen_open_weather_map.memcached.class%'
        arguments:
            - '$memcached_settings.server;netgen_open_weather_map$'
            - '$memcached_settings.port;netgen_open_weather_map$'
    # END of Cache services

    # OpenWeatherMap services
    netgen_open_weather_map.weather:
        class: '%netgen_open_weather_map.weather.class%'
        arguments:
            - '@netgen_open_weather_map.http.client'
            - '$api_settings.api_key;netgen_open_weather_map$'
            - '@netgen_open_weather_map.cache_handler'
            - '$cache_settings.ttl;netgen_open_weather_map$'
            - '$api_settings.units;netgen_open_weather_map$'
            - '$api_settings.language;netgen_open_weather_map$'
            - '$api_settings.type;netgen_open_weather_map$'

    netgen_open_weather_map.air_pollution:
        class: '%netgen_open_weather_map.air_pollution.class%'
        arguments:
            - '@netgen_open_weather_map.http.client'
            - '$api_settings.api_key;netgen_open_weather_map$'
            - '@netgen_open_weather_map.cache_handler'
            - '$cache_settings.ttl;netgen_open_weather_map$'

    netgen_open_weather_map.daily_forecast:
        class: '%netgen_open_weather_map.daily_forecast.class%'
        arguments:
            - '@netgen_open_weather_map.http.client'
            - '$api_settings.api_key;netgen_open_weather_map$'
            - '@netgen_open_weather_map.cache_handler'
            - '$cache_settings.ttl;netgen_open_weather_map$'
            - '$api_settings.units;netgen_open_weather_map$'
            - '$api_settings.language;netgen_open_weather_map$'
            - '$api_settings.type;netgen_open_weather_map$'

    netgen_open_weather_map.hour_forecast:
        class: '%netgen_open_weather_map.hour_forecast.class%'
        arguments:
            - '@netgen_open_weather_map.http.client'
            - '$api_settings.api_key;netgen_open_weather_map$'
            - '@netgen_open_weather_map.cache_handler'
            - '$cache_settings.ttl;netgen_open_weather_map$'
            - '$api_settings.units;netgen_open_weather_map$'
            - '$api_settings.language;netgen_open_weather_map$'
            - '$api_settings.type;netgen_open_weather_map$'

    netgen_open_weather_map.ultraviolet_index:
        class: '%netgen_open_weather_map.ultraviolet_index.class%'
        arguments:
            - '@netgen_open_weather_map.http.client'
            - '$api_settings.api_key;netgen_open_weather_map$'
            - '@netgen_open_weather_map.cache_handler'
            - '$cache_settings.ttl;netgen_open_weather_map$'

    netgen_open_weather_map.weather_stations:
        class: '%netgen_open_weather_map.weather_stations.class%'
        arguments:
            - '@netgen_open_weather_map.http.client'
            - '$api_settings.api_key;netgen_open_weather_map$'
            - '@netgen_open_weather_map.cache_handler'
            - '$cache_settings.ttl;netgen_open_weather_map$'
    # END of OpenWeatherMap services

    # Controllers
    netgen_open_weather_map.controller.weather:
        class: '%netgen_open_weather_map.controller.weather.class%'
        arguments:
            - '@netgen_open_weather_map.weather'

    netgen_open_weather_map.controller.weather_stations:
        class: '%netgen_open_weather_map.controller.weather_stations.class%'
        arguments:
            - '@netgen_open_weather_map.weather_stations'

    netgen_open_weather_map.controller.ultraviolet_index:
        class: '%netgen_open_weather_map.controller.ultraviolet_index.class%'
        arguments:
            - '@netgen_open_weather_map.ultraviolet_index'

    netgen_open_weather_map.controller.hour_forecast:
        class: '%netgen_open_weather_map.controller.hour_forecast.class%'
        arguments:
            - '@netgen_open_weather_map.hour_forecast'

    netgen_open_weather_map.controller.daily_forecast:
        class: '%netgen_open_weather_map.controller.daily_forecast.class%'
        arguments:
            - '@netgen_open_weather_map.daily_forecast'

    netgen_open_weather_map.controller.air_pollution:
        class: '%netgen_open_weather_map.controller.air_pollution.class%'
        arguments:
            - '@netgen_open_weather_map.air_pollution'
    # END of Controllers
